export enum EmodjiName {
    SUCCESS_CHECK = 'SUCCESS_CHECK',
    FLYING_MONEY = 'FLYING_MONEY',
    WEED_GESTURE = 'WEED_GESTURE',
    MONEY_STACK = 'MONEY_STACK',
    MONEY_BAG = 'MONEY_BAG',
    HANDSHAKE = 'HANDSHAKE',
    TARGET = 'TARGET',
    FRIEND = 'FRIEND',
    ARROW_RIGHT = 'ARROW_RIGHT',
    BREAD = 'BREAD',
}